# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json if available
COPY package*.json ./

# Install dependencies (ignoring scripts to skip prepare if necessary)
RUN npm install --ignore-scripts

# Copy the rest of the application code
COPY . .

# Build the project
RUN npm run build

# Expose any necessary port (if applicable, MCP uses stdio so not needed)

# Command to run the MCP server
CMD [ "node", "build/index.js" ]
